build: off

platform:
  - x64

image:
  - Visual Studio 2015

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      TOXENV: "py27"
        
    - PYTHON: "C\\Python34-x64"
      TOXENV: "py34"

    - PYTHON: "C\\Python35-x64"
      TOXENV: "py35"

    - PYTHON: "C:\\Python36-x64"
      TOXENV: "py36"

install:
  - 'python -m pip install tox'
  - 'python -m pip install wheel'
 
test_script:
  - 'python -m tox'

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
