dist: trusty
sudo: required

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

notifications:
  email: false

install:
  - pip install -U tox-travis pip
  - pip install -r requirements.txt

script:
  # Build and test extension module
  - python setup.py build_ext --inplace
  - LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/tiledb:$LD_LIBRARY_PATH" python -m unittest tiledb.tests.all.suite_test
  - # LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/tiledb:$LD_LIBRARY_PATH" python -m doctest tiledb/libtiledb.pyx
  # Check wheel build
  - python setup.py bdist_wheel
  - whl_file=`pwd`/dist/`ls dist`
  - pushd /tmp
  - echo "Installing wheel file from $whl_file..."
  - pip install $whl_file
  - python -c "import tiledb ; tiledb.libtiledb.version()"
  - python $TRAVIS_BUILD_DIR/examples/quickstart_dense.py
  - python $TRAVIS_BUILD_DIR/examples/quickstart_sparse.py
  - python $TRAVIS_BUILD_DIR/examples/quickstart_kv.py
  - python $TRAVIS_BUILD_DIR/examples/reading_dense_layouts.py
  - python $TRAVIS_BUILD_DIR/examples/reading_sparse_layouts.py
  - python $TRAVIS_BUILD_DIR/examples/writing_dense_multiple.py
  - python $TRAVIS_BUILD_DIR/examples/writing_dense_padding.py
  - python $TRAVIS_BUILD_DIR/examples/writing_sparse_multiple.py
  - python $TRAVIS_BUILD_DIR/examples/config.py
  - python $TRAVIS_BUILD_DIR/examples/errors.py
  - python $TRAVIS_BUILD_DIR/examples/fragments_consolidation.py
  - python $TRAVIS_BUILD_DIR/examples/kv.py
  - python $TRAVIS_BUILD_DIR/examples/multi_attribute.py
  - rm -rf my_group && python $TRAVIS_BUILD_DIR/examples/object.py
  - python $TRAVIS_BUILD_DIR/examples/vfs.py