language: python

python:
  - "3.6"

sudo: false

notifications:
  email: false

install:
  - pip install -U tox-travis coveralls pip setuptools wheel
  - pip install -r requirements_dev.txt
  - python setup.py build_ext --inplace

script:
  - python -m unittest -v

after_success:
  - coveralls
