language: python

python:
  - "3.6"

sudo: false

notifications:
  email: false

# command to install dependencies
install: "pip install -r requirements_dev.txt"

# command to run tests
script: pytest
